CREATE TABLE itsadate_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_name TEXT NOT NULL,
    description VARCHAR NOT NULL,
    event_time VARCHAR(5) NOT NULL,
    location VARCHAR NOT NULL,
    other VARCHAR,
    day_id INTEGER NOT NULL,
    calendar_id INTEGER REFERENCES itsadate_calendars(id) ON DELETE CASCADE NOT NULL
);